# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    build: mediawiki/
    restart: always
    ports:
      - 8088:80
    # volumes:
    #   - /var/www/html/images
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
  database:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mediawiki-datavolume:/var/lib/mysql
  node-services:
    build: node-services/
    ports:
      - 7231:7231
      - 8000:8142
    environment:
      MEDIAWIKI_API_URL: http://mediawiki/api.php
      MEDIAWIKI_URL: http://mediawiki
      PARSOID_URL: http://parsoid:8000
  mem:
    image: memcached
    expose: 
      - 11211
  mathmoid:
    image: nlpub/mathoid
volumes:
  mediawiki-datavolume:
