FROM centos:6
LABEL maintainer="loveress01@gmail.com"

# basically, it will build server according to the mediawiki setup guide

WORKDIR /root

RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo \
&& curl -sL https://rpm.nodesource.com/setup_6.x | bash - \
&&  yum makecache \
&& yum install -y nodejs git


RUN cd /root \
&& git clone https://github.com/wikimedia/restbase.git \
&& rm -rf restbase/.git/ 

RUN cd restbase \
&& npm install \
&& npm cache clean --force

WORKDIR /root/restbase

RUN mkdir -p /data
COPY . /data/
VOLUME /data/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 7231

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "node","./bin/server.js" ]