FROM centos:6
LABEL maintainer="loveress01@gmail.com"
# refer to 

# you can change this two

WORKDIR /root

RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo \
&& curl -sL https://rpm.nodesource.com/setup_6.x | bash - \
&&  yum makecache \
&& yum install -y nodejs git


RUN cd /root \
&& git clone --recursive https://gerrit.wikimedia.org/r/p/mediawiki/services/parsoid/deploy \
&& git clone https://gerrit.wikimedia.org/r/p/mediawiki/services/parsoid \
&& rm -rf deploy/.git/ deploy/src/.git/ parsoid/.git/ \
&& cd parsoid \
&& npm install \
&& npm cache clean --force

WORKDIR /root/parsoid

RUN mkdir -p /data
COPY . /data/
VOLUME /data/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8000

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "node","./bin/server.js" ]