FROM centos:6
LABEL maintainer="loveress01@gmail.com"
# refer to 

WORKDIR /root/parsoid
# you can change this two

RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo \
&&  yum makecache \
&&  yum install git nodejs

RUN git clone --recursive https://gerrit.wikimedia.org/r/p/mediawiki/services/parsoid/deploy \
&& git clone https://gerrit.wikimedia.org/r/p/mediawiki/services/parsoid \
&& cd parsoid \
&& npm install \
&& npm cache clean --force

RUN mkdir -p /data
COPY . /data/
VOLUME /data/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "node","server.js" ]